version: '3.7'

services:
  apella-guide:
    build: ./
    container_name: apella-guide
    restart: always
    env_file:
      - ./env/apella-guide.env
    # ports:
    #   - "8000:8000"
    expose:
      - "8000"
    volumes:
      - ./src/:/usr/share/nginx/html:ro
    networks:
      - janus_apella-net

# Networks in use
networks:
  janus_apella-net:
    external: true
