version: '3.7'

services:
  apella-guide:
    build: ./
    container_name: apella-guide
    restart: always
    env_file:
      - ./env/apella-guide.env
    expose:
      - "8000"
    volumes:
      - ./src/:/var/www/servers/apella-guide/
    networks:
      - janus_apella-net

# Networks in use
networks:
  janus_apella-net:
    external: true
