version: '3.7'

services:
  concordia-guide:
    build: ./
    container_name: concordia-guide
    restart: always
    env_file:
      - ./env/concordia-guide.env
    expose:
      - "8000"
    volumes:
      - ./src/:/var/www/servers/concordia-guide/
    networks:
      - ecentrics_concordia_production_network

# Networks in use
networks:
  ecentrics_concordia_production_network:
    external: true
